version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_SLUG}_nginx
    volumes:
      - ${APP_PATH}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_SLUG}.rule=Host(`${PROJECT_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_SLUG}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_SLUG}.tls.certresolver=${TRAEFIK_RESOLVER}"
    networks:
      - app
      - traefik

  php:
    image: php:8.2-fpm
    container_name: ${PROJECT_SLUG}_php
    volumes:
      - ${APP_PATH}:/var/www/html
    networks:
      - app

  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_SLUG}_mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${PROJECT_SLUG}_mysql_data:/var/lib/mysql
    networks:
      - app

volumes:
  ${PROJECT_SLUG}_mysql_data:

networks:
  app:
  traefik:
    external: true
